
from fpdf import FPDF

def build_pdf(scan, product, violations, out_path):
    p = FPDF(); p.add_page(); p.set_font("helvetica", "B", 16)
    p.cell(0, 10, "Legal Metrology Compliance Report", ln=True, align="C")
    p.set_font("helvetica", "", 10)
    p.cell(0, 6, f"Product: {product['name']}   |   Scan ID: {scan['id']}   |   Status: {scan['status']}", ln=True)
    p.ln(4); p.set_font("helvetica", "B", 12); p.cell(0, 8, "Extracted Declarations", ln=True)
    p.set_font("helvetica", "", 9)
    import json
    ex = json.loads(scan["extracted"] or "{}")
    for k in ("mrp", "net_qty", "date", "phone", "email", "imported"):
        p.cell(0, 5, f"{k}: {ex.get(k)}", ln=True)
    p.ln(4); p.set_font("helvetica", "B", 12); p.cell(0, 8, "Violations", ln=True)
    p.set_font("helvetica", "", 9)
    if not violations: p.cell(0, 5, "No violations detected.", ln=True)
    for v in violations:
        p.multi_cell(0, 5, f"[{v['severity']}] Rule {v['rule_id']}: {v['message']}")
    p.ln(4); p.set_font("helvetica", "I", 8)
    p.multi_cell(0, 4, "Evidence: label photograph attached in scan record. This report is generated by an automated screening system and does not replace adjudication under the Legal Metrology Act, 2009.")
    p.output(out_path)
