const $ = s => document.querySelector(s);
function escapeHtml(v) { return String(v ?? '').replace(/[&<>'"]/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c])); }
let ocrWorker = null, ruleChart = null, severityChart = null;
async function api(url, options = {}) { const r = await fetch(url, {credentials:'same-origin', ...options}); if (!r.ok) { let m = `Request failed (${r.status})`; try { m = (await r.json()).detail || m; } catch (_) {} throw new Error(m); } return r.json(); }
function showApp(role) { $('#login').classList.add('hidden'); $('#app').classList.remove('hidden'); $('#userRole').textContent = role ? role.toUpperCase() : ''; }
async function checkSession() { try { const m = await api('/api/auth/me'); if (m.authenticated) showApp(m.role); } catch (_) {} }
$('#loginForm').onsubmit = async e => { e.preventDefault(); $('#loginError').textContent=''; try { const fd = new FormData(); fd.append('password', $('#loginPassword').value); fd.append('requested_role', $('#loginRole').value); const r = await api('/api/auth/login', {method:'POST', body:fd}); $('#loginPassword').value=''; showApp(r.role); } catch(e) { $('#loginError').textContent=e.message; } };
$('#logout').onclick = async () => { await api('/api/auth/logout',{method:'POST'}); location.reload(); };
document.querySelectorAll('.tab').forEach(b => b.onclick = () => { document.querySelectorAll('.tab').forEach(x => x.classList.remove('active')); document.querySelectorAll('.page').forEach(x => x.classList.add('hidden')); b.classList.add('active'); $('#' + b.dataset.tab).classList.remove('hidden'); if (b.dataset.tab === 'history') loadHistory(); if (b.dataset.tab === 'dash') loadDash(); });
$('#img').onchange = () => { const file=$('#img').files[0]; if(!file)return; $('#preview').src=URL.createObjectURL(file); $('#previewWrap').classList.remove('hidden'); };
async function browserOCR(file) { if (typeof Tesseract === 'undefined') return ''; $('#go').textContent = 'Preparing OCR fallback…'; if (!ocrWorker) ocrWorker = await Tesseract.createWorker('eng'); const { data } = await ocrWorker.recognize(file); return data.text || ''; }
function fieldValue(obj) { if (!obj) return '—'; if (Array.isArray(obj.value)) return obj.value.join(' '); return obj.value || '—'; }
function renderFields(f) { const names=[['product_name','Product name'],['mrp','MRP'],['net_qty','Net quantity'],['date','Manufacture/packing date'],['consumer_care','Consumer care'],['manufacturer','Manufacturer/packer'],['origin','Country of origin'],['importer','Importer'],['best_before','Best before'],['font_mm','Estimated MRP font (mm)']]; $('#fields').innerHTML=names.map(([k,n])=>`<div class="field"><span>${escapeHtml(n)}</span><b>${escapeHtml(fieldValue(f[k]))}</b><small>${f[k]?.confidence!=null ? Math.round(f[k].confidence*100)+'% confidence' : ''}</small></div>`).join(''); }
$('#go').onclick = async () => { const file = $('#img').files[0]; if (!file) return alert('Pick a label photo first.'); if (file.size > 10 * 1024 * 1024) return alert('Image must be 10 MB or smaller.'); const button=$('#go'); button.disabled=true; $('#error').textContent=''; try { let browserText=''; if (!$('#demo').value.trim()) { try { browserText=await browserOCR(file); } catch(e) { console.warn('Browser OCR fallback unavailable',e); } } const fd=new FormData(); fd.append('file',file); fd.append('category',$('#category').value); if($('#ppm').value)fd.append('px_per_mm',$('#ppm').value); if($('#demo').value.trim())fd.append('demo_text',$('#demo').value.trim()); else if(browserText)fd.append('client_ocr',browserText); button.textContent='Analyzing label…'; const result=await api('/api/scan',{method:'POST',body:fd}); $('#result').classList.remove('hidden'); const status=$('#status'); status.textContent=result.status.replaceAll('_',' '); status.className='status-pill '+(result.status==='COMPLIANT'?'good':result.status==='NON_COMPLIANT'?'bad':'review'); $('#r_product').textContent=fieldValue(result.extracted.product_name); $('#r_category').textContent=result.category; $('#r_engine').textContent=result.engine; $('#r_findings').textContent=result.violations.length; renderFields(result.extracted); $('#viol').innerHTML=result.violations.length?result.violations.map(v=>`<li class="${escapeHtml(v.severity)}"><b>[${escapeHtml(v.severity)}]</b> ${escapeHtml(v.rule_id)} — ${escapeHtml(v.message)}${v.evidence?`<small>${escapeHtml(typeof v.evidence==='string'?v.evidence:JSON.stringify(v.evidence))}</small>`:''}</li>`).join(''):'<li class="ok">No critical or major issues flagged. Continue manual inspection.</li>'; $('#ocrRaw').textContent=result.extracted.raw||''; $('#pdf').href='/api/report/'+encodeURIComponent(result.scan_id)+'.pdf'; $('#docx').href='/api/report/'+encodeURIComponent(result.scan_id)+'.docx'; $('#confidence').textContent=`OCR confidence: ${Math.round((result.extracted.ocr_confidence||0)*100)}% • Engine: ${result.engine} • Scan ID: ${result.scan_id}`; } catch(e) { $('#error').textContent=e.message; $('#result').classList.add('hidden'); } finally { button.disabled=false; button.textContent='Analyze Label'; } };
async function loadHistory() { try { const params=new URLSearchParams(); if($('#search').value.trim())params.set('q',$('#search').value.trim()); if($('#statusFilter').value)params.set('status',$('#statusFilter').value); if($('#categoryFilter').value)params.set('category',$('#categoryFilter').value); const rows=await api('/api/scans?'+params.toString()); $('#tbl').innerHTML='<tr><th>ID</th><th>Product</th><th>Category</th><th>Status</th><th>Date</th><th>Report</th></tr>'+rows.map(s=>`<tr><td>${escapeHtml(s.id)}</td><td>${escapeHtml(s.product_name)}</td><td>${escapeHtml(s.category)}</td><td class="${s.status==='COMPLIANT'?'ok':s.status==='REVIEW_REQUIRED'?'review':'bad'}">${escapeHtml(s.status.replaceAll('_',' '))}</td><td>${escapeHtml(new Date(s.created_at*1000).toLocaleString())}</td><td><a href="/api/report/${encodeURIComponent(s.id)}.pdf" target="_blank" rel="noopener">PDF</a> <a href="/api/report/${encodeURIComponent(s.id)}.docx" target="_blank" rel="noopener">DOCX</a></td></tr>`).join(''); } catch(e) { $('#tbl').innerHTML=`<tr><td colspan="6" class="bad">${escapeHtml(e.message)}</td></tr>`; } }
$('#refresh').onclick=loadHistory; $('#search').onkeydown=e=>{if(e.key==='Enter')loadHistory();};
async function loadDash() { try { const d=await api('/api/dashboard'); $('#k_total').textContent=d.total_scans; $('#k_nc').textContent=d.non_compliant; $('#k_review').textContent=d.review_required; $('#k_rate').textContent=d.compliance_rate+'%'; if(ruleChart)ruleChart.destroy(); if(severityChart)severityChart.destroy(); ruleChart=new Chart($('#ch_rule'),{type:'bar',data:{labels:d.violations_by_rule.map(x=>x.rule_id),datasets:[{label:'Findings',data:d.violations_by_rule.map(x=>x.c)}]},options:{responsive:true,maintainAspectRatio:false}}); severityChart=new Chart($('#ch_sev'),{type:'doughnut',data:{labels:d.violations_by_severity.map(x=>x.severity),datasets:[{data:d.violations_by_severity.map(x=>x.c)}]},options:{responsive:true,maintainAspectRatio:false}}); } catch(e){console.error(e);} }
checkSession();
